# These are supported funding model platforms

Patreon:
https://www.patreon.com/SystymaticDevelopment/shop/donation-1541426?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=productshare_creator&utm_content=join_link
